#!/usr/bin/env python3
"""Generate the Android adaptive launcher icon from <repo>/icon.png.

    python scripts/make-launcher-icon.py        (needs Pillow: pip install pillow)

icon.png is a rounded-square artwork on a near-white canvas. Launchers mask adaptive icons with their own
shape and only show the middle 72dp of the 108dp layer, so this script:
  1. makes the near-white area outside the rounded square transparent (flood fill from the four corners),
  2. scales the artwork to ARTWORK_DP inside the 108dp foreground layer, so a squircle mask (Samsung) cuts
     nothing - the text and hearts reach the artwork's edge; a circular mask (Pixel) still clips its corners,
  3. writes the foreground at every density and a background colour sampled from the artwork's rim.

Outputs (all committed):
  app/src/main/res/mipmap-*/ic_launcher_foreground.png
  app/src/main/res/values/ic_launcher_background.xml
"""
import os
import sys

from PIL import Image, ImageDraw

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SOURCE = os.path.join(REPO, "icon.png")
RES = os.path.join(REPO, "app", "src", "main", "res")

LAYER_DP = 108          # adaptive icon layer size
ARTWORK_DP = 70         # artwork edge inside the layer; the mask shows at most the middle 72dp
DENSITIES = {"mdpi": 1.0, "hdpi": 1.5, "xhdpi": 2.0, "xxhdpi": 3.0, "xxxhdpi": 4.0}
WHITE_TOLERANCE = 48    # how far from the corner colour still counts as "outside" (eats the anti-aliased rim)


def cut_out_canvas(image: Image.Image) -> Image.Image:
    """Turn the near-white canvas outside the rounded square transparent."""
    rgba = image.convert("RGBA")
    w, h = rgba.size
    for corner in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)]:
        ImageDraw.floodfill(rgba, corner, (0, 0, 0, 0), thresh=WHITE_TOLERANCE)
    return rgba


def rim_colour(rgba: Image.Image) -> tuple:
    """Median colour of the artwork's rim: opaque pixels in thin strips just inside each edge's midpoint."""
    w, h = rgba.size
    inset, half = int(w * 0.035), int(w * 0.12)
    samples = []
    for x in range(w // 2 - half, w // 2 + half, 3):
        samples += [rgba.getpixel((x, inset)), rgba.getpixel((x, h - 1 - inset))]
    for y in range(h // 2 - half, h // 2 + half, 3):
        samples += [rgba.getpixel((inset, y)), rgba.getpixel((w - 1 - inset, y))]
    opaque = [p for p in samples if p[3] == 255]
    if not opaque:
        sys.exit("could not sample the rim colour - is the artwork smaller than expected?")
    channel = lambda i: sorted(p[i] for p in opaque)[len(opaque) // 2]
    return channel(0), channel(1), channel(2)


def main() -> None:
    if not os.path.exists(SOURCE):
        sys.exit(f"missing {SOURCE}")
    artwork = cut_out_canvas(Image.open(SOURCE))
    artwork = artwork.crop(artwork.getchannel("A").getbbox())  # trim the transparent margin
    colour = rim_colour(artwork)

    for name, scale in DENSITIES.items():
        layer_px = round(LAYER_DP * scale)
        art_px = round(ARTWORK_DP * scale)
        layer = Image.new("RGBA", (layer_px, layer_px), (0, 0, 0, 0))
        resized = artwork.resize((art_px, art_px), Image.LANCZOS)
        offset = (layer_px - art_px) // 2
        layer.paste(resized, (offset, offset), resized)
        folder = os.path.join(RES, f"mipmap-{name}")
        os.makedirs(folder, exist_ok=True)
        layer.save(os.path.join(folder, "ic_launcher_foreground.png"), optimize=True)
        print(f"mipmap-{name}: {layer_px}px layer, {art_px}px artwork")

    values = os.path.join(RES, "values")
    os.makedirs(values, exist_ok=True)
    with open(os.path.join(values, "ic_launcher_background.xml"), "w", encoding="utf-8", newline="\n") as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n')
        f.write("<!-- Generated by scripts/make-launcher-icon.py: rim colour of icon.png. -->\n")
        f.write("<resources>\n")
        f.write('    <color name="ic_launcher_background">#%02X%02X%02X</color>\n' % colour)
        f.write("</resources>\n")
    print("background colour #%02X%02X%02X" % colour)


if __name__ == "__main__":
    main()
